### PR TITLE
Fix CYaml/module.modulemap using relative path

### PR DESCRIPTION
**Pull request by takasek**
With absolute path I cannot build the project.

### CODE REVIEW

**Comment by ikesyo** [comment]
This is a result of `swift package generate-xcodeproj` so automating the replacement in Makefile would be great I think.

**Comment by ikesyo** [comment]
Ref: https://github.com/apple/swift-package-manager/pull/1406

**Comment by ishkawa** [comment]
🙈

+1 for automating the replacement!

**Comment by takasek** [comment]
@ikesyo Oh, thank you for your advice, but it is too tough for me...
Could anyone fix the problem instead of me?

**Comment by ikesyo** [comment]
How about something like this:

```diff
diff --git a/Makefile b/Makefile
index ae3da88..7fecc79 100644
--- a/Makefile
+++ b/Makefile
@@ -15,3 +15,4 @@ set_version:
 
 generate_xcodeproj:
 	swift package generate-xcodeproj --xcconfig-overrides ${XCCONFIG_PATH}
+	perl -pe 's|".+/(\.build/checkouts/Yams\.git.+)"|"../../../$1"|' -i DIKit.xcodeproj/GeneratedModuleMap/CYaml/module.modulemap
```

**Comment by takasek** [comment]
In my environment,  it works with duplicating `$`.

```
perl -pe 's|".+/(\.build/checkouts/Yams\.git.+)"|"../../../$$1"|' -i DIKit.xcodeproj/GeneratedModuleMap/CYaml/module.modulemap
```

However, running `make generate_xcodeproj` extraordinary affects existing files.
Especially it changes the versions from `0.3.0` to `1.0.0`.
Any advice to fix it?

**Comment by ishkawa** [comment]
Okay, we found it's not so easy to automate xcodeproj generation now. Let's separate the task into 2 peaces, fixing current modulemap and automating xcodeproj generation. This PR does the former task, and I will tackle to the latter task later.

I'm going to merge this PR, thank you @takasek!

**Pull request merged**
